theme: jekyll-theme-primer
markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
title: "Obsei: An open-source low-code AI powered automation tool"
description: "Obsei is an open-source low-code AI powered automation tool"

google_analytics: G-0E2FTKBK4T
