name: obsei
channels:
- conda-forge
- anaconda
- lalitpagaria
dependencies:
- python
- pytorch
- pytz
- atlassian-python-api
- elasticsearch
- pydantic
- python-dateutil
- sqlalchemy
- google-api-python-client
- app-store-reviews-reader
- reddit-rss-reader
- praw
- mmh3
- beautifulsoup4
- slack-sdk
- sentencepiece
- vadersentiment
- transformers
- pandas
- nltk
- numpy
- pip
- pip:
  - presidio-analyzer
  - presidio-anonymizer
  - zenpy
  - searchtweets-v2
  - google-play-scraper
  - tweet-preprocessor
  - gnews
  - trafilatura
  - python-facebook-api
