name: release draft

on:
  workflow_dispatch:

jobs:
  draft-release:
#    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_DRAFT_TOKEN }}